[package]
name = "apt-repo-crawler"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
license = "MIT"

[dependencies]
url-crawler = { path = "../url-crawler" }
chrono = "0.4.6"
